INSERT INTO items (item_name, notes) VALUES
('Bluetooth Speaker Portable', 'Waterproof IPX7 rating. Battery lasts 12 hours. Available in 6 colors. Customer feedback highlights bass quality.'),
('Smart Watch Fitness Tracker', 'Heart rate monitor and GPS included. Syncs with iOS and Android. Band replacement kits sold separately. Return rate 4.2%.'),
('Wireless Earbuds Sports', 'Sweat-resistant design rated IPX5. Ear hook keeps buds secure during workouts. Charging case provides 30 hours total. Popular with gym-goers.'),
('Digital Alarm Clock LED', 'Large 6-inch display with auto dimming. Dual alarm settings. USB charging port on back. Shipping weight under 400g.'),
('Portable DAC Amplifier', 'Supports 32-bit 384kHz audio. USB-C and Lightning adapters included. Audiophile-grade components. Small batch production limits stock to 200 units per month.'),
('Smart Doorbell Camera', '1080p video with night vision. Two-way audio. Motion detection zones configurable via app. Requires existing doorbell wiring. Installation guide included.'),
('TV Antenna Indoor HD', 'Receives channels within 50-mile radius. Paper-thin design mounts behind TV. Coaxial cable included. No monthly fees. Popular cord-cutting accessory.'),
('Power Bank Solar 20000mAh', 'Dual USB output ports. Solar panel provides emergency charging. Carabiner clip for backpack attachment. TSA approved for flights.'),
('FM Transmitter Bluetooth Car', 'Plugs into cigarette lighter. Hands-free calling capability. Supports USB flash drive playback. QC3.0 fast charging port. Frequency range 87.5 to 108MHz.'),
('Digital Kitchen Scale', 'Measures in grams and ounces. Tare function for container weight. Stainless steel platform. Battery included. Accuracy within 1 gram.'),
('Smart Light Bulb WiFi', '16 million color options. Dimmable from 1% to 100%. Voice control via Alexa and Google. No hub required. Energy Star certified. 800 lumens output.'),
('USB Flash Drive 128GB', 'Metal housing with keyring hole. Read speeds up to 150MB per second. Compatible with USB 3.0 and 2.0. Lifetime warranty from manufacturer.'),
('Wireless Keyboard Compact', 'Bluetooth 5.0 connectivity. Rechargeable battery lasts 3 months. Scissor switch keys for quiet typing. Multi-device pairing up to 3 devices.'),
('HDMI Splitter 4K 1x2', 'Supports 4K at 60Hz and HDR10. Powered via USB for stable signal. Compatible with gaming consoles and streaming devices. No driver needed.'),
('Smart Thermostat WiFi', 'Learning algorithm adjusts temperature automatically. Energy savings estimated at 15% on heating bills. Requires C-wire or adapter kit sold separately.'),
('Portable Radio AM FM', 'Analog tuner with clear reception. Runs on AA batteries or DC adapter. Headphone jack included. Compact size fits in a jacket pocket.'),
('Electric Pencil Sharpener', 'Helical blade for precise sharpening. Auto-stop feature prevents over-sharpening. Shavings reservoir easy to empty. Runs on USB power or batteries.'),
('Digital Photo Frame 10in', 'IPS display with 1280x800 resolution. WiFi enabled for remote photo uploads. Slideshow with transitions. Internal storage holds 10000 photos. Gift-ready packaging.'),
('Cable Tester Network RJ45', 'Tests Cat5 Cat6 and Cat7 cables. LED indicators for each wire pair. Battery operated and portable. Essential tool for IT departments.'),
('Mini Projector LED Pocket', '854x480 native resolution. Built-in speaker. HDMI and USB input. Battery provides 1.5 hours of playback. Focus wheel for manual adjustment.'),
('Voltage Converter Travel', 'Converts 220V to 110V for US devices abroad. 200W capacity for small electronics. Compact design with universal plug adapters. Thermal fuse protection.'),
('Wireless Charger Stand Duo', 'Charges phone and earbuds simultaneously. Qi certified up to 15W. LED indicator with night mode dimming. Anti-slip base. Compatible with MagSafe cases.'),
('Smart Plug Power Strip', '4 outlets individually controllable via app. Surge protection 1080 joules. Voice control compatible. Scheduling and timer functions built in.'),
('USB Microphone Wireless', '2.4GHz wireless with 30m range. Clip-on lapel design. Receiver plugs into USB-C. Battery lasts 8 hours. Ideal for presentations and video calls.'),
('Streaming Media Player 4K', 'Supports Netflix, Disney Plus, and all major services. Voice remote included. Dual-band WiFi. Dolby Atmos audio. Compact stick form factor.'),
('Battery Charger Rechargeable', 'Charges AA and AAA NiMH batteries. LCD display shows charge progress. Independent channel charging. Auto shutoff when complete. Includes 4 AA batteries.'),
('Ethernet Switch 5-Port', 'Gigabit speeds on all ports. Plug and play unmanaged. Metal housing for heat dissipation. Fanless silent operation. LED activity indicators per port.'),
('Smart Scale Body Composition', 'Measures weight, BMI, body fat, and muscle mass. Syncs with Apple Health and Google Fit. Tempered glass platform. Supports up to 400 lbs.'),
('Noise Cancelling Adapter', 'Adds ANC to any wired headphones. Rechargeable with 20-hour battery. 3.5mm passthrough design. Three ANC levels adjustable via button.'),
('Digital Voice Recorder', '32GB internal storage records 1000 hours. One-touch recording. USB transfer to computer. Playback speed adjustable. Voice-activated recording mode available.'),
('Electric Kettle Glass 1.7L', 'Borosilicate glass body with blue LED. Auto shutoff at boiling. BPA-free construction. Keep-warm function holds temperature 30 minutes. Descaling instructions included.'),
('Air Fryer Compact 3.5Qt', 'Digital touchscreen with 8 presets. Dishwasher-safe basket. Cooks with 85% less oil. Recipe booklet included. Customer satisfaction rating 4.7 stars.'),
('Immersion Blender Stainless', '300W motor with variable speed control. Includes whisk and chopper attachments. Ergonomic grip design. Shaft detaches for easy cleaning. BPA-free.'),
('Pour Over Coffee Dripper', 'Ceramic construction retains heat. Fits standard mugs and carafes. Size 02 uses standard cone filters. Handwash only. Available in white and matte black.'),
('Cast Iron Skillet 12in', 'Pre-seasoned and ready to use. Works on all cooktops including induction. Oven safe to 500 degrees. Helper handle for heavy lifting. Lifetime warranty.'),
('Vegetable Spiralizer Manual', 'Creates 3 noodle sizes from vegetables. Suction cup base for stability. BPA-free blades. Dishwasher safe. Popular with health-conscious customers. Low return rate 1.8%.'),
('Electric Can Opener', 'Smooth-edge cutting leaves no sharp lids. Opens standard and pop-top cans. Magnetic lid holder. Runs on 2 AA batteries. Compact countertop design.'),
('Silicone Baking Mat Set', 'Fits half-sheet pans. Non-stick surface rated to 480 degrees. FDA approved food-grade silicone. Set of 3 mats. Replaces parchment paper. Eco-friendly packaging.'),
('Spice Grinder Electric', 'Grinds whole spices in 10 seconds. Stainless steel blade and cup. One-touch operation. Capacity 80 grams. Cord-free for easy storage. Also works for coffee beans.'),
('Digital Meat Thermometer', 'Instant read in 3 seconds. Waterproof IP67 rated. Backlit display. Magnet and hook for storage. Foldable probe. Accuracy within 0.5 degrees Fahrenheit.'),
('French Press Coffee 34oz', 'Double-wall stainless steel keeps coffee hot 2 hours. 4-level filtration system. Dishwasher safe. Available in copper, silver, and matte black finishes.'),
('Mandoline Slicer Adjustable', '5 thickness settings from 1mm to 8mm. Safety guard and cut-resistant glove included. Stainless steel blade. Julienne and waffle cut options. Handwash recommended.'),
('Milk Frother Electric Handheld', 'Creates foam in 15 seconds. Runs on 2 AA batteries. Stainless steel whisk. Stand included for storage. Works with all milk types including oat and almond.'),
('Bamboo Cutting Board Large', '18x12 inch surface. Juice groove catches liquids. Organic bamboo is knife-friendly. Hand wash and oil monthly. Engraving available for corporate gifts.'),
('Salad Spinner Large', '5-quart capacity. Pull-cord mechanism for easy spinning. Non-slip base. Bowl doubles as serving dish. BPA-free. Dishwasher safe. Locks for storage.'),
('Ice Cream Maker 1.5Qt', 'Built-in compressor requires no pre-freezing. Makes ice cream in 25 minutes. LCD timer display. Includes recipe book. Customer feedback requests larger capacity version.'),
('Herb Garden Kit Indoor', 'Includes 6 seed pods with grow lights. Self-watering system with indicator. Basil, parsley, cilantro, dill, mint, and chives included. Replacement pods available.'),
('Electric Wine Opener', 'Opens bottle in 5 seconds. Rechargeable battery opens 80 bottles per charge. Foil cutter included. LED indicator for battery level. Gift box packaging available.'),
('Sous Vide Precision Cooker', 'WiFi enabled with app control. Temperature accurate to 0.1 degrees. 1100W heating element. Clamp fits pots up to 8 inches deep. IPX7 waterproof rating.'),
('Cold Brew Coffee Maker', '1.5-liter glass pitcher. Fine mesh filter for smooth extraction. BPA-free lid. Brews concentrate in 12-24 hours. Dishwasher safe components.'),
('Pizza Stone Round 15in', 'Cordierite stone withstands 1500 degrees. Absorbs moisture for crispy crust. Includes wooden pizza peel. Season before first use. Allow to cool gradually to prevent cracking.'),
('Citrus Juicer Manual Press', 'Heavy-duty cast iron construction. Extracts maximum juice with minimal effort. Fits lemons, limes, and small oranges. Suction cup base. Easy to clean.'),
('Food Storage Containers 24pc', 'Borosilicate glass with snap-lock lids. Oven, microwave, and freezer safe. Nesting design saves cabinet space. Leak-proof seal tested. BPA-free lids.'),
('Egg Timer Color Changing', 'Changes color as egg cooks to indicate soft, medium, or hard boiled. Silicone construction. Reusable and dishwasher safe. No batteries needed. Novelty gift item.'),
('Compost Bin Kitchen Counter', '1.3-gallon capacity. Charcoal filter eliminates odors. Stainless steel exterior. Includes 4 replacement filters. Attractive enough for countertop display.'),
('Waffle Maker Belgian Style', 'Non-stick plates for easy release. Indicator light signals when ready. Makes 7-inch round waffles. Cord wrap for storage. Vertical storage saves counter space.'),
('Tea Infuser Bottle Glass', 'Double-wall borosilicate glass. Removable stainless steel infuser basket. Neoprene sleeve for grip and insulation. 450ml capacity. Bamboo lid.'),
('Knife Sharpener Electric 3-Stage', 'Coarse, fine, and honing stages restore any blade. Diamond abrasive wheels. Non-slip rubber feet. Works on straight and serrated edges. 2-year warranty.'),
('Insulated Food Jar 16oz', 'Keeps food hot 7 hours or cold 9 hours. Wide mouth for easy eating. Stainless steel interior. BPA-free. Includes folding spork. Popular for school lunches.'),
('Produce Storage Containers', 'Vented design keeps fruits and vegetables fresh longer. Set of 3 sizes. Clear lids for visibility. BPA-free. Dishwasher safe. Extends produce life by 2x.'),
('Cordless Drill Driver 20V', 'Includes 2 lithium-ion batteries. 2-speed gearbox for drilling and driving. LED work light. 21 clutch positions. Carrying case and bit set included. Contractor-grade quality.'),
('Tape Measure 25ft Heavy Duty', 'Nylon-coated blade resists wear. Magnetic hook grips metal surfaces. Belt clip included. Blade lock mechanism. Rubber overmold for drop protection. Imperial and metric markings.'),
('Level Torpedo Magnetic', '9-inch aluminum body. 3 vials for plumb, level, and 45-degree readings. Rare earth magnets hold to steel surfaces. V-groove fits pipes. Shock-absorbing endcaps.'),
('Socket Set 40-Piece Metric', 'Chrome vanadium steel for durability. Quick-release ratchet mechanism. Sizes from 4mm to 19mm. Blow-molded case for organization. Lifetime warranty against defects.'),
('Utility Knife Retractable', 'Quick-change blade mechanism. Stores 5 blades in handle. Non-slip rubber grip. Wire stripping notch. Lanyard hole for safety attachment. Includes 10 replacement blades.'),
('Adjustable Wrench 10in', 'Chrome-plated forged alloy steel. Wide jaw capacity of 1-3/16 inches. Laser-etched measurement markings. Slim profile for tight spaces. Comfort grip handle.'),
('Stud Finder Digital', 'Detects wood and metal studs. AC wire detection mode for safety. LCD display with center-finding indicator. Requires 9V battery. Calibrates automatically at startup.'),
('Hex Key Set Ball End 9pc', 'Long-arm design for extended reach. Ball end allows 25-degree offset entry. Color-coded sizes for quick identification. Chrome vanadium steel. Metric sizes 1.5mm to 10mm.'),
('Wire Stripper Automatic', 'Adjusts to wire gauge automatically. Strips 10-24 AWG wire. Built-in cutter and crimper. Spring-loaded handles reduce fatigue. Insulated handles rated to 1000V.'),
('Pliers Set 5-Piece', 'Includes needle-nose, diagonal, slip-joint, groove-joint, and lineman pliers. Drop-forged steel construction. Ergonomic bi-material grips. Vinyl roll-up pouch included.'),
('Caulk Gun Drip-Free', '10:1 thrust ratio for smooth application. Built-in cutter and seal puncture tool. Drip-free mechanism. Fits standard 10oz cartridges. Lightweight frame design.'),
('Screwdriver Set Precision 6pc', 'Includes 3 Phillips and 3 flathead sizes. Rotating cap for fine control. Chrome vanadium steel shafts. Magnetized tips. Storage case with snap closure.'),
('Clamp Bar Quick-Grip 12in', 'One-hand trigger operation. Spreader function reverses jaws. 300 lb clamping force. Non-marring pads protect workpiece. Available in 6, 12, and 24 inch sizes.'),
('Hammer Claw 16oz Fiberglass', 'Fiberglass handle absorbs vibration. Forged steel head. Smooth face for finishing work. Anti-vibration grip. Balanced weight distribution. Meets ANSI standards.'),
('Multitool Pocket 14-in-1', 'Stainless steel construction. Includes pliers, knife, saw, file, screwdrivers, and more. Nylon belt sheath included. Locking blades for safety. TSA prohibited for carry-on.'),
('Drill Bit Set Titanium 29pc', 'Titanium nitride coating for extended life. 135-degree split point starts on contact. Sizes 1/16 to 1/2 inch. Metal index case for organization. For metal, wood, and plastic.'),
('Ratchet Wrench Set Flex-Head', '72-tooth ratcheting mechanism. 5-degree swing arc for tight spaces. Flex-head pivots 180 degrees. Sizes 8mm to 19mm. Mirror chrome finish. Full polish.'),
('Safety Glasses Clear 12-Pack', 'ANSI Z87.1 rated impact protection. Anti-fog coated lenses. Scratch-resistant polycarbonate. Lightweight at 26 grams. UV protection. Bulk pricing for contractors.'),
('Laser Level Self-Leveling', 'Projects cross-line pattern. Accuracy within 1/8 inch at 30 feet. Self-leveling within 4 degrees. Mounting bracket included. Runs on AA batteries for 12 hours.'),
('Tool Bag Heavy Duty 16in', '1680D polyester fabric. 20 interior and exterior pockets. Reinforced bottom prevents wear. Padded shoulder strap. Water-resistant coating. Holds up to 50 lbs.'),
('Pry Bar Set 3-Piece', 'Includes 8-inch, 12-inch, and 18-inch bars. High-carbon steel. Ground and polished edges. Strike cap on handle for hammer use. Ideal for demolition and renovation.'),
('Digital Caliper 6-Inch', 'Stainless steel construction. Measures inside, outside, depth, and step. Resolution 0.001 inches. LCD display with auto off. Includes carrying case. Zero reset button.'),
('Chisel Set Wood 4-Piece', 'Chrome vanadium steel blades. Hardwood handles with metal strike caps. Sizes 1/4, 1/2, 3/4, and 1 inch. Honed edge ready to use. Leather tool roll included.'),
('Riveter Pop Rivet Hand', 'Sets 3/32, 1/8, 5/32, and 3/16 inch rivets. Spring-loaded handle for easy operation. Includes 100 assorted rivets. Aluminum body is lightweight. Nosepiece wrench stored in handle.'),
('Workbench Portable Folding', 'Holds up to 350 lbs. Bamboo top surface 24x48 inches. Folds flat for storage. Adjustable height. Includes 4 bench dogs and 2 clamps. Quick setup in under a minute.'),
('Sanding Block Flexible', 'Contours to curved surfaces. Accepts standard sandpaper sheets. EVA foam core. Available in fine and medium grit. Comfortable hand grip. Wet or dry sanding capable.'),
('Voltage Tester Non-Contact', 'Detects voltage from 50V to 1000V AC. LED and audible alert. Auto power off saves battery. Pocket clip for easy carry. CAT IV safety rated. Flashlight built in.'),
('Pipe Wrench 14-Inch', 'Heavy-duty cast iron. I-beam handle resists bending. Precision-machined hook jaw. Replaceable jaw inserts. Epoxy-coated for corrosion resistance.'),
('Staple Gun Heavy Duty', 'Fires T50 staples and 18-gauge brad nails. All-steel construction. Easy-squeeze mechanism reduces effort by 50%. Bottom-load magazine. Quick-jam clear.'),
('Hacksaw Adjustable Frame', 'Accepts 10 and 12-inch blades. 90-degree and 180-degree blade positions. High-tension frame for straight cuts. Comfort grip handle. Includes 2 bi-metal blades.'),
('Camping Hammock Double', 'Supports up to 500 lbs. Parachute nylon fabric. Includes tree straps and carabiners. Packs into attached stuff sack. Triple stitched seams for durability.'),
('Hiking Backpack 40L', 'Ventilated back panel keeps you cool. Rain cover included in bottom pocket. Hydration bladder compatible. Adjustable torso length. Hip belt distributes weight effectively.'),
('Headlamp LED Rechargeable', '350 lumens maximum brightness. Red light mode preserves night vision. USB-C rechargeable. IPX5 water resistant. Runs 6 hours on high and 40 hours on low.'),
('Water Filter Straw Portable', 'Removes 99.99% of bacteria and parasites. Filters up to 1000 gallons. No batteries or moving parts. Weighs only 2 ounces. Essential emergency preparedness item.'),
('Camping Stove Butane Portable', '8000 BTU output. Piezo ignition for matchless lighting. Wind guards improve efficiency. Fits standard butane canisters. Carrying case included. Not for indoor use.'),
('Trekking Poles Carbon Fiber', 'Ultralight at 7.5 ounces per pole. Cork grips absorb sweat. Quick-lock adjustment from 24 to 54 inches. Tungsten carbide tips. Snow baskets included.'),
('Dry Bag Waterproof 20L', 'Roll-top closure with buckle. Welded seams prevent leaks. Transparent window for visibility. D-ring attachment points. Available in high-visibility orange and blue.'),
('Camping Lantern LED Solar', '400 lumens with 4 light modes. Solar panel and USB charging. Collapsible design for compact storage. Built-in power bank charges devices. Emergency strobe mode.'),
('Insect Repellent Bracelet 10pk', 'DEET-free citronella and lemongrass formula. Each bracelet effective for 72 hours. Adjustable wrist and ankle fit. Safe for children over 3. Individually sealed.'),
('Fire Starter Magnesium Rod', 'Works when wet. Produces 5500-degree sparks. Includes steel striker. Lasts 12000 strikes. Lanyard hole for attachment. Survival gear essential. Compact and lightweight.'),
('Binoculars Compact 10x25', 'Multi-coated optics for bright images. Foldable roof prism design. 273-foot field of view at 1000 yards. Rubber armored body. Includes neck strap and carry case.'),
('Outdoor Blanket Waterproof', 'Fleece top with waterproof PEVA backing. 79x55 inches unfolds for family use. Folds into carry handle. Machine washable fleece side. Stake loops in corners.'),
('Survival Whistle Emergency', '120 decibel sound carries over 1 mile. Includes compass, thermometer, and signal mirror. Lanyard attached. Lightweight ABS plastic. Essential for every outdoor kit.'),
('Carabiner Clip Heavy Duty 4pk', 'Rated to 12kN. Aircraft-grade aluminum. Wire gate design for easy clipping. NOT for climbing or life safety. Ideal for gear organization and key rings.'),
('Camping Chair Ultralight', 'Supports 300 lbs. Weighs only 2 lbs. Breathable mesh seat. Aluminum frame. Packs into included carry bag. Cup holder on armrest. Setup in 30 seconds.'),
('Trail Mix Organic 2lb Bag', 'Almonds, cashews, raisins, dark chocolate chips, and coconut flakes. USDA organic certified. Nut allergy warning prominent on label. Resealable bag. Best by date 12 months.'),
('Compass Navigation Lensatic', 'Military-grade aluminum housing. Luminous markings for night use. Sighting wire and lens for precision. Liquid-dampened needle. Lanyard included. Works without batteries.'),
('Paracord Bracelet Survival', '12 feet of 550 paracord when unraveled. Includes whistle buckle, fire starter, and compass. Adjustable wrist size. Available in 8 colors. Popular impulse buy item.'),
('Portable Water Purifier UV', 'Destroys 99.9% of viruses and bacteria. Treats 16oz in 48 seconds. USB rechargeable with 80 treatment cycles. Compact pen design. Lab tested and certified.'),
('Hammock Rain Fly Tarp', 'Silnylon construction with PU coating. 12x10 feet coverage. Includes guylines and stakes. Weighs 22 ounces. Ridgeline sleeve for easy setup. Protects hammock in rain.'),
('Solar Panel Portable 21W', 'Foldable 3-panel design. Dual USB output charges 2 devices. 22% conversion efficiency. IPX4 splash resistant. Carabiner clips for backpack mounting.'),
('Mosquito Net Camping Bed', 'Fine 256-mesh netting blocks smallest insects. Fits cots and sleeping bags. Single entry point with zipper. Compact stuff sack included. Treated with permethrin.'),
('Tactical Flashlight 1000 Lumen', 'Aircraft-grade aluminum body. 5 modes including strobe and SOS. IPX8 waterproof submersible. Zoomable focus. Runs on rechargeable 18650 or 3 AAA batteries.'),
('Outdoor Thermometer Wireless', 'Transmits temperature and humidity to indoor display. 330-foot range. Records daily high and low. Weather-resistant sensor. Mounts with screw or adhesive.'),
('Kayak Paddle Adjustable', 'Aluminum shaft adjusts from 84 to 94 inches. Fiberglass-reinforced nylon blades. Drip rings prevent water running to hands. Breaks down into 2 pieces for transport.'),
('Camping Cookware Set 10pc', 'Hard-anodized aluminum. Includes 2 pots, frying pan, plates, cups, and utensils. Nesting design packs into mesh carry bag. Non-stick coating. Total weight 2.2 lbs.'),
('Emergency Blanket Mylar 10pk', 'Reflects 90% of body heat. Windproof and waterproof. Each blanket 52x82 inches. Compact folded size. Essential first aid and survival item. Shelf life unlimited.'),
('Hiking Gaiters Waterproof', 'Prevents debris from entering boots. Waterproof and breathable fabric. Adjustable top and bottom closures. Boot hook keeps gaiter in place. Available in S/M and L/XL.'),
('Campfire Cooking Grate', 'Heavy-duty steel with chrome plating. 24x16 inch surface. Foldable legs adjust height. Supports heavy pots. Portable with included carry bag. Season before first use.'),
('Tarp Stakes Aluminum 12pk', 'Y-beam design resists rotation. 7-inch length for solid hold. Ultralight at 0.4 oz each. Reflective pull cord attached. Color-coded for easy retrieval from ground.'),
('Resistance Bands Set 5pc', 'Latex-free TPE material. Resistance levels from 5 to 50 lbs. Color-coded by difficulty. Includes door anchor and handles. Carrying bag for portability. Exercise guide included.'),
('Yoga Mat Non-Slip 6mm', 'TPE eco-friendly material. 72x24 inch size. Alignment lines printed on surface. Carrying strap included. Closed-cell surface prevents sweat absorption. Available in 8 colors.'),
('Jump Rope Speed Adjustable', 'Ball-bearing handles for smooth rotation. Steel cable with PVC coating. Adjustable length up to 10 feet. Memory foam grips. Ideal for double-unders and HIIT training.'),
('Foam Roller High Density', '13-inch length, 5.5-inch diameter. EVA foam maintains shape. Textured surface for deep tissue massage. Supports up to 300 lbs. Physical therapist recommended.'),
('Kettlebell Vinyl Coated 25lb', 'Cast iron core with vinyl shell. Flat bottom for floor stability. Wide handle fits two hands. Color-coded weight identification. Floor-safe coating. Sold individually.'),
('Pull-Up Bar Doorframe', 'Fits doorways 26 to 36 inches wide. Supports up to 300 lbs. No screws required for installation. Padded grips prevent blisters. Multiple grip positions. Compact storage.'),
('Dumbbell Set Adjustable 50lb', 'Replaces 15 sets of dumbbells. Dial system changes weight in 5 lb increments. Compact tray design. Durable molding around plates. 2-year warranty on mechanism.'),
('Exercise Ball Anti-Burst 65cm', 'Supports up to 600 lbs. Slow-deflation if punctured. Includes foot pump. GS certified. Use as desk chair alternative. Textured surface for grip.'),
('Ankle Weights Adjustable 5lb', 'Removable weight bars allow 1-5 lb adjustment. Neoprene exterior is comfortable. Velcro strap secures firmly. Sold as pair. Moisture-wicking lining reduces sweat.'),
('Ab Roller Wheel', 'Dual-wheel design for stability. Ergonomic foam handles. Includes knee pad. Builds core strength effectively. Compact and portable. Steel axle rated for heavy use.'),
('Battle Rope 30ft', '1.5-inch diameter poly-dacron blend. Handles heat-shrink wrapped. Anchor strap included for wrapping posts. Develops grip strength and cardio conditioning.'),
('Agility Ladder 20ft', '12 adjustable rungs lock in place. Heavy-duty nylon straps. Improves footwork and coordination. Carrying bag included. Used by pro athletes and trainers.'),
('Medicine Ball Rubber 10lb', 'Textured rubber shell for secure grip. Consistent bounce for wall ball exercises. Color indicates weight. Diameter 9 inches. Suitable for CrossFit and circuit training.'),
('Workout Gloves Leather', 'Full-grain leather palms. Ventilated mesh backing. Wrist wrap support. Pull tab for easy removal. Machine washable. Available in S through XL. Unisex design.'),
('Push-Up Board System', 'Color-coded positions target different muscles. Non-slip base. Foldable and portable. Includes workout poster. Supports up to 350 lbs. Assembly-free design.'),
('Suspension Trainer System', 'Adjustable straps 36 to 84 inches. Mounts to door, tree, or beam. Full-body workout with bodyweight. Carrying bag and workout guide. Commercial-grade materials.'),
('Massage Gun Percussion', '6 speed settings up to 3200 PPM. 4 interchangeable heads. Brushless motor for quiet operation. 6-hour battery life. Carrying case included. Helps muscle recovery.'),
('Yoga Block Cork 2-Pack', 'Natural cork is firm and supportive. 4x6x9 inch standard size. Non-slip surface even when wet. Sustainable material. Beveled edges for comfort. Lightweight at 1 lb each.'),
('Wrist Wraps Weightlifting', '18-inch length with thumb loop. Hook and loop closure. Heavy-duty elastic. Provides joint stabilization during pressing movements. Sold as pair. Available in 6 designs.'),
('Gymnastic Rings Wood', 'Birch wood rings 1.25-inch grip diameter. Numbered straps adjust to 15 feet. 600 lb weight capacity. Cambuckle for quick height changes. Smooth sanded finish.'),
('Skipping Rope Weighted', '1 lb handles add resistance. Ball-bearing swivel for smooth rotation. PVC rope adjustable to 9.5 feet. Counter in handle tracks revolutions. Batteries included.'),
('Stretch Strap Yoga 10 Loop', 'Cotton/nylon blend. 10 individual loops for progressive stretching. 6 feet total length. Used in physical therapy. Includes stretching guide booklet.'),
('Grip Strengthener Adjustable', 'Resistance adjustable from 22 to 132 lbs. Ergonomic aluminum handles. Knurled grip surface. Compact enough for desk use. Builds forearm and hand strength.'),
('Balance Board Wobble', '16-inch diameter non-slip surface. Develops core stability and balance. Holds up to 350 lbs. Use standing or for push-ups. Physical therapy tool. ABS plastic construction.'),
('Boxing Hand Wraps 180in', 'Semi-elastic cotton blend. Thumb loop and hook-and-loop closure. Protects wrists and knuckles. Machine washable. Sold in pair. Multiple colors. Competition length.'),
('Barbell Pad Squat Sponge', 'High-density foam cushion. Fits standard and Olympic bars. Velcro closure secures position. Reduces neck and shoulder pressure. 17 inches long. Non-slip interior.'),
('Parallette Bars Steel Pair', '12-inch height for dip and L-sit exercises. Non-slip rubber feet. Rated to 400 lbs. Powder-coated steel. Compact enough for home gym. 24-inch base length.'),
('Rowing Machine Resistance Band', 'Simulates rowing motion. Adjustable resistance via band count. Foot pedals with straps. LCD display tracks reps and time. Folds flat under bed or couch.'),
('Plyo Box Foam 3-in-1', '20x24x30 inch dimensions. High-density foam core. Vinyl cover with non-slip surface. Eliminates shin scrape risk. Weighs 35 lbs. Used for box jumps and step-ups.'),
('Speed Parachute Running', '48-inch canopy creates resistance. Adjustable waist belt. Quick-release buckle. Improves sprint acceleration. Nylon construction is durable. Used by track coaches and football players.'),
('Dog Harness No-Pull Medium', 'Front clip design discourages pulling. Padded chest plate for comfort. Reflective stitching for night visibility. 4 adjustment points for custom fit. Machine washable.'),
('Cat Tree Tower 60in', 'Sisal-wrapped scratching posts. 3 platforms with plush covering. Hammock and condo hideaway. Ceiling height 60 inches. Base 24x24 inches. Assembly hardware included.'),
('Automatic Pet Feeder WiFi', 'Schedules up to 6 meals daily. Portion control from 1 to 39 servings. Voice recording calls pet to eat. WiFi app control. Battery backup during power outage. Holds 4 liters.'),
('Dog Bed Orthopedic Large', 'Memory foam base supports joints. Removable washable cover. Non-slip bottom. 40x30x4 inches. Recommended by veterinarians for senior dogs. Waterproof liner protects foam.'),
('Cat Litter Mat Waterproof', 'Honeycomb design traps litter from paws. 30x24 inches fits beside any litter box. Waterproof bottom layer. Easy to clean with vacuum or shake. Durable EVA material.'),
('Dog Leash Retractable 16ft', 'One-button brake and lock. Ergonomic handle with anti-slip grip. Reflective tape on leash. Supports dogs up to 110 lbs. Tangle-free design. ABS housing is drop-resistant.'),
('Pet Water Fountain 2L', 'Circulating filter removes impurities. Ultra-quiet pump at 30dB. BPA-free construction. Triple filtration system. LED indicator when water is low. Replacement filters sold separately.'),
('Dog Toy Rope Tug 3-Pack', '100% cotton rope is safe if ingested. Machine washable. Promotes dental health through chewing. Assorted sizes for different breeds. Bright colors for visibility.'),
('Cat Brush Self-Cleaning', 'Retractable bristle button clears fur instantly. Stainless steel pins with rounded tips. Reduces shedding by 90%. Ergonomic handle. Works on all coat types and lengths.'),
('Dog Treat Training Pouch', 'Magnetic closure for quick access. Belt clip and waist strap options. Built-in waste bag dispenser. Reflective trim. Multiple pockets for phone and keys. Wipeable interior.'),
('Pet Nail Clipper LED Light', 'Built-in LED illuminates quick to prevent cutting too deep. Safety guard limits cut depth. Stainless steel blades. Ergonomic handles. Suitable for dogs and cats.'),
('Dog Raincoat Waterproof Medium', 'Adjustable belly strap. Leash hole on back. Reflective piping for visibility. Lightweight nylon material. Easy on and off with velcro closures. Available in yellow and green.'),
('Cat Tunnel Collapsible 3-Way', 'Crinkle material stimulates play. 10-inch diameter fits most cats. Peephole for ambush play. Folds flat for storage. Durable polyester construction. Interactive dangling toy.'),
('Dog Bowl Slow Feeder', 'Maze pattern reduces eating speed by 5x. Prevents bloat and vomiting. BPA-free food-grade plastic. Dishwasher safe. Non-slip rubber base. Holds 2 cups of food.'),
('Pet GPS Tracker Collar', 'Real-time tracking via cellular network. Geofence alerts when pet leaves area. Waterproof IP67. Battery lasts 5 days. Requires monthly subscription for service. Weighs 25 grams.'),
('Dog Dental Chew Toy', 'Natural rubber with mint flavor. Textured ridges clean teeth. Holds treats inside for engagement. Dishwasher safe. Vet recommended. Available in 3 sizes based on dog weight.'),
('Cat Window Perch Suction', 'Industrial suction cups hold up to 40 lbs. 24x12 inch platform. Machine washable fleece cover. Easy install on any window. Provides bird-watching entertainment for indoor cats.'),
('Pet First Aid Kit', '45 essential items for emergencies. Includes bandages, antiseptic, tweezers, and emergency blanket. Compact zippered case. Reference guide with instructions. Travel-friendly size.'),
('Dog Poop Bag Dispenser 300ct', 'Leak-proof extra-thick bags. Lavender scented for odor control. Attaches to any leash with clip. Rolls fit all standard dispensers. Eco-friendly EPI additive for degradation.'),
('Cat Scratching Post Sisal', '32 inches tall. Heavy base prevents tipping. Natural sisal rope fiber. Plush top perch. Dangling pom-pom toy. Saves furniture from scratching damage. Ships fully assembled.'),
('Pet Carrier Airline Approved', 'Fits under most airline seats. Ventilated mesh panels on 3 sides. Padded shoulder strap. Fleece bedding included. TSA compliant. Interior safety clip attaches to collar.'),
('Dog Cooling Mat Pressure', 'Gel-activated cooling without electricity or refrigeration. 36x20 inches for large dogs. Puncture-resistant outer material. Wipes clean with damp cloth. Reactivates automatically.'),
('Cat Interactive Toy Feather', 'Battery-operated rotating feather. Unpredictable movement mimics prey. Auto shutoff after 15 minutes. Replacement feathers available. Engages natural hunting instinct.'),
('Pet Stain Remover Enzyme', 'Breaks down organic stains and odors at molecular level. 32oz spray bottle. Safe for carpets, upholstery, and hardwood. Non-toxic formula. Works on old and new stains.'),
('Dog Seatbelt Car Harness', 'Crash-tested to 75 lbs. Clips into standard seatbelt buckle. Adjustable length 16 to 27 inches. Padded chest piece. Swivel clip prevents tangling. Meets safety standards.'),
('Car Phone Mount Magnetic', 'N52 neodymium magnets. Dashboard and vent clip options included. 360-degree rotation. Works with all phone cases. Does not interfere with GPS. Adhesive rated for extreme heat.'),
('Tire Pressure Gauge Digital', 'Accuracy within 0.5 PSI. Backlit LCD display. Measures 0-150 PSI. Auto shutoff after 30 seconds. Includes batteries. Bleeder valve releases excess pressure.'),
('Jump Starter Portable 1500A', 'Starts engines up to 7.0L gas or 5.5L diesel. Built-in USB power bank. LED flashlight with SOS mode. Safety clamps with reverse polarity protection. Holds charge 6 months.'),
('Dash Cam Front 1080p', 'Loop recording on microSD card. G-sensor locks footage during collision. Parking mode monitors when car is off. Wide 170-degree lens. Suction cup and adhesive mounts.'),
('Car Vacuum Cordless Handheld', '7000PA suction power. Rechargeable lithium battery runs 25 minutes. HEPA filter captures fine dust. Includes crevice and brush nozzles. Compact storage in trunk.'),
('Seat Gap Filler 2-Pack', 'Fills gap between seat and console. Prevents phones and keys from falling. Universal fit for all vehicles. PU leather exterior matches interiors. Easy installation.'),
('Windshield Sun Shade Foldable', 'Custom-fit reflective material. Reduces cabin temperature up to 40 degrees. Folds to 10-inch diameter. Elastic band keeps it compact. UV protection preserves dashboard.'),
('Car Air Freshener Vent Clip 6pk', 'Solid fragrance lasts 30 days each. No liquid spill risk. Rotating clip adjusts intensity. Available in ocean, lavender, and pine scents. Minimalist design.'),
('Emergency Road Kit 66-Piece', 'Includes jumper cables, flashlight, first aid supplies, and warning triangle. Reflective safety vest. Tire gauge and rain poncho. Durable zippered case fits in trunk.'),
('Car Trash Can Collapsible', '2.5-gallon capacity. Waterproof interior lining. Velcro strap attaches to headrest. Foldable when not in use. Lid keeps odors contained. Machine washable exterior.'),
('OBD2 Scanner Bluetooth', 'Reads and clears engine codes. Compatible with all 1996+ vehicles. Free app for iOS and Android. Real-time data monitoring. Emission readiness check. Compact design.'),
('Steering Wheel Lock Bar', 'Visible theft deterrent. Fits wheels 10 to 16 inches diameter. Hardened steel construction. 2 keys included. Bright red color is intentionally conspicuous. Quick install.'),
('Car Seat Organizer Back', 'Multiple pockets for tablets, bottles, and toys. Clear tablet holder with touch capability. Durable Oxford fabric. Easy install with adjustable straps. Kick mat protects seat.'),
('Tire Inflator Portable 12V', 'Plugs into car cigarette lighter. Inflates standard tire in 5 minutes. Digital pressure gauge with auto shutoff. Includes adapters for bikes and sports balls. 10-foot power cord.'),
('LED Headlight Bulbs H11 Pair', '6000K bright white output. 300% brighter than halogen. 50000-hour lifespan. Plug-and-play installation. Built-in fan for cooling. DOT compliant for road use.'),
('Car Wax Spray Ceramic', 'SiO2 ceramic coating in spray form. Hydrophobic surface repels water. UV protection prevents oxidation. Apply in 15 minutes. Lasts up to 6 months. 16oz bottle.'),
('Blind Spot Mirrors 2-Pack', '2-inch convex mirrors. Adjustable 360-degree swivel. 3M adhesive backing. Reduces blind spots significantly. HD glass for clear reflection. Stick onto existing mirrors.'),
('Battery Terminal Cleaner', 'Wire brush removes corrosion from terminals. Tapered design fits top and side posts. Comfortable handle. Extends battery life with regular maintenance. Made in USA.'),
('Trunk Organizer Collapsible', '3 compartments with adjustable dividers. Non-slip bottom grips carpet. Side pockets for small items. Folds flat when empty. Reinforced walls maintain shape when loaded.'),
('Car Charger Dual USB-C', '45W total output. Power Delivery fast charging. Compatible with all USB-C devices. Aluminum body dissipates heat. LED ring indicator. Compact low-profile design.'),
('Leather Belt Reversible', 'Black and brown sides. Rotating buckle switches colors. Full-grain leather. Available in sizes 32 to 44. 1.25-inch width. Gift box packaging. Suitable for dress and casual.'),
('Wool Scarf Merino Winter', '100% merino wool. 72x12 inches. Naturally temperature regulating. Itch-free superfine grade. Available in charcoal, navy, and burgundy. Dry clean recommended.'),
('Watch Band Silicone 22mm', 'Quick-release spring bars. Waterproof and sweat-proof. Fits Samsung, Fossil, and most 22mm lug watches. Available in 12 colors. Hypoallergenic material.'),
('Sunglasses Polarized Sport', 'UV400 protection blocks 99.9% of UV rays. Polarized lenses reduce glare. TR90 flexible frame. Rubberized nose pads. Includes hard case and microfiber cloth.'),
('Wallet RFID Blocking Slim', 'Top-grain leather construction. Holds 8 cards and cash. RFID protection verified by independent lab. Gift-ready packaging. Dimensions 4.5x3.5x0.5 inches. Available in 4 colors.'),
('Beanie Knit Fleece Lined', 'Acrylic exterior with micro-fleece lining. One size fits most. Stretchy ribbed knit. Machine washable. Available in 10 colors. Ideal for cold weather and outdoor activities.'),
('Umbrella Windproof Compact', 'Withstands 55 mph winds. Auto open and close button. Teflon-coated canopy repels water. Fiberglass ribs prevent inversion. Carrying sleeve included. 42-inch arc.'),
('Tie Clip Stainless Steel', 'Brushed stainless steel finish. 2.15-inch length fits standard ties. Strong spring tension. Gift box included. Available in silver, gold, and black. Suitable for professional wear.'),
('Gloves Touchscreen Winter', 'Conductive fingertips work with all touchscreens. Fleece-lined for warmth. Silicone grip on palms. Elastic wrist cuff. Available in M and L. Machine washable.'),
('Hat Baseball Adjustable', '6-panel structured crown. Pre-curved visor. Adjustable snapback closure. Cotton twill fabric. Available in 15 colors. Embroidery-ready blank. One size fits most adults.'),
('Cufflinks Silver Set', 'Sterling silver plated. Classic torpedo bullet back closure. Includes matching tie bar. Velvet-lined presentation box. Engraving available on request. Timeless design.'),
('Suspenders Y-Back Elastic', '1.4-inch wide elastic straps. Heavy-duty clips grip firmly. Adjustable length to 50 inches. Available in solid colors and patterns. Suitable for formal and casual wear.'),
('Socks Athletic Ankle 6-Pack', 'Moisture-wicking polyester blend. Cushioned sole absorbs impact. Arch compression for support. Reinforced heel and toe. Sizes M and L. Machine wash cold.'),
('Pocket Square Silk Set 5pc', '100% mulberry silk. Pre-folded for easy insertion. Assorted patterns complement suits. 10x10 inches each. Hand roll edge stitching. Dry clean only.'),
('Hair Clip Claw Large 4pk', 'Strong grip holds thick hair securely. Matte finish in neutral tones. Non-slip teeth design. 4 inches long. Durable cellulose acetate. Tortoiseshell and black included.'),
('Backpack Drawstring Gym', '210D polyester. Cinch cord closure. Front zipper pocket. Reinforced corners. Available with custom printing for events. Lightweight at 4 ounces. Popular promotional item.'),
('Bow Tie Silk Pre-Tied', '100% silk fabric. Adjustable neck band 13.5 to 18.5 inches. Pre-tied for consistent appearance. Available in solid and patterned designs. Gift box packaging.'),
('Earrings Stud Hypoallergenic 6pr', 'Surgical steel posts. CZ stones 4mm, 5mm, and 6mm pairs. Nickel-free for sensitive ears. Push-back closures. Gift card included. Suitable for daily wear.'),
('Belt Bag Canvas Crossbody', 'Water-resistant cotton canvas. Adjustable strap 28 to 52 inches. 3 zippered compartments. Fits phone, wallet, and keys. Available in earth tones. Unisex design.'),
('Watch Minimalist Quartz', 'Japanese quartz movement. 40mm stainless steel case. Genuine leather strap. Water resistant to 30 meters. Sapphire-coated crystal resists scratches. 2-year battery life.'),
('Colored Pencil Set 72pc', 'Premium cedar wood barrels. Soft core for smooth blending. Break-resistant leads. Tin case with organized tray. Lightfast pigments. Artist-grade quality at student price.'),
('Acrylic Paint Set 24 Tubes', '12ml tubes in assorted colors. Fast-drying water-based formula. Suitable for canvas, paper, and wood. Non-toxic AP certified. Mixable for custom colors.'),
('Sketchbook Hardbound 9x12', '110 sheets of 80lb acid-free paper. Micro-perforated for clean removal. Suitable for pencil, pen, and light marker. Lay-flat binding. Elastic closure band.'),
('Watercolor Pan Set 36 Colors', 'Half-pan format in folding palette. Includes water brush pen. Pigments are vibrant and mixable. Compact for plein air painting. Metal case is durable for travel.'),
('Brush Set Synthetic 10pc', 'Assorted shapes: round, flat, filbert, and detail. Synthetic nylon bristles. Short handles for detail work. Suitable for acrylic, watercolor, and oil. Ferrules crimped not glued.'),
('Canvas Stretched 16x20 2-Pack', 'Triple-primed cotton duck canvas. Staple-free edges. 5/8-inch profile. Ready to paint. Acid-free priming. Suitable for oil and acrylic. Kiln-dried stretcher bars.'),
('Calligraphy Pen Set Starter', '3 nib sizes included: fine, medium, and broad. Cartridge and converter fill system. Instruction booklet with practice sheets. Gift-ready tin case. Smooth ink flow.'),
('Pastel Soft Set 48 Colors', 'Square format prevents rolling. Rich pigment concentration. Low dust formula. Suitable for paper, board, and canvas. Includes half and full sticks. Protective foam tray.'),
('Easel Tabletop Adjustable', 'Beechwood construction. Adjusts to 3 positions. Holds canvas up to 20 inches. Folds flat for storage. Rubber feet protect surfaces. Suitable for display and painting.'),
('Ink Set Drawing 6 Colors', 'India ink in 1oz bottles. Waterproof when dry. Dropper cap for controlled dispensing. Suitable for dip pens, brushes, and airbrush. Archival quality.'),
('Palette Wooden Oval', '12x16 inch oval shape. Smooth sanded birch wood. Thumb hole for comfortable holding. Seal with varnish before first use. Traditional design preferred by oil painters.'),
('Charcoal Sticks Vine Set', 'Soft, medium, and hard grades included. Natural willow vine charcoal. 6 inches long. Creates expressive marks. Ideal for life drawing. Fixative recommended for permanence.'),
('Marker Set Alcohol-Based 40pc', 'Dual tip: broad chisel and fine point. Blendable and fast-drying. Refillable with replacement ink. Compatible with smooth marker paper. Organized carrying case.'),
('Paper Mixed Media 9x12 Pad', '184lb heavyweight paper. 15 sheets per pad. Suitable for wet and dry media. Acid-free and archival. Textured surface holds color. Tape-bound edges.'),
('Modeling Clay Air-Dry 5lb', 'Dries in 24-48 hours without kiln. White color paintable when dry. Non-toxic and odorless. Smooth consistency for sculpting. Store unused portion in airtight bag.'),
('Eraser Set Art 4-Pack', 'Includes kneaded, gum, vinyl, and precision eraser. Kneaded eraser is reusable. Vinyl eraser for clean removal. Precision eraser for fine detail. Essential for graphite work.'),
('Gouache Paint Set 12 Tubes', 'Opaque water-based paint. 12ml tubes. Matte finish when dry. Rewettable for blending. Suitable for illustration and design. Colors can be thinned to watercolor consistency.'),
('Printmaking Ink Water-Based', 'Easy soap-and-water cleanup. 8oz jar. Rich black pigment. Suitable for linocut and woodblock printing. Non-toxic formula. Dries in 30 minutes on paper.'),
('Drawing Pencil Set Graphite 12pc', 'Grades from 6B to 4H. Cedar wood casings. Smooth and consistent leads. Suitable for sketching and technical drawing. Tin case with grade chart. Pre-sharpened.'),
('Spray Fixative Workable 12oz', 'Prevents smudging of pastel, charcoal, and graphite. Workable formula allows additional layers. Acid-free and archival. Use in well-ventilated area. Matte finish.'),
('Guitar Strings Acoustic Set', 'Phosphor bronze wound. Light gauge .012-.053. Bright and balanced tone. Coated for extended life. 6 strings per set. Compatible with all standard acoustic guitars.'),
('Ukulele Soprano Mahogany', 'Laminate mahogany body. Geared tuners hold pitch reliably. Aquila Nylgut strings installed. 21-inch scale length. Includes gig bag, tuner, and chord chart.'),
('Metronome Digital Clip-On', 'Tempo range 30-250 BPM. LCD display with beat counter. Clip attaches to music stand or instrument. Tap tempo function. Runs on CR2032 battery. Headphone jack.'),
('Harmonica Key of C 10-Hole', 'Phosphor bronze reeds. ABS comb body. Diatonic major scale. Suitable for blues, folk, and rock. Includes protective case. Beginner-friendly with online lessons.'),
('Drum Sticks Hickory 5A Pair', 'American hickory wood. Nylon tip for bright cymbal sound. 16-inch length. Balanced weight at 52 grams each. Lacquer finish for grip. Industry standard size.'),
('Guitar Capo Quick-Change', 'Spring-loaded single-hand operation. Fits acoustic and electric guitars. Silicone pad protects frets. Strong clamping force eliminates buzz. Available in black and silver.'),
('Keyboard Stand X-Style', 'Adjustable height from 27 to 37 inches. Holds up to 90 lbs. Double-braced legs for stability. Rubber end caps protect floors. Folds flat for transport.'),
('Violin Rosin Premium', 'Produces smooth and even tone. Low dust formula keeps instrument clean. Suitable for violin, viola, and cello bows. Wooden case with cloth. Natural amber rosin.'),
('Guitar Tuner Clip-On', '360-degree rotating display. Chromatic mode for all instruments. Fast and accurate detection. Auto power off saves battery. Bright LCD visible on stage.'),
('Music Stand Folding Portable', 'Adjustable height 27 to 57 inches. Wide tray holds full sheet music. Steel construction with powder coat finish. Carry bag included. Rubber feet prevent sliding.'),
('Recorder Soprano Baroque', 'ABS resin body. Baroque fingering system. Includes cleaning rod and fingering chart. 3-piece design. C tuning. Standard school music instrument. Carry bag included.'),
('Guitar Pick Variety 40-Pack', 'Celluloid picks in thin, medium, and heavy gauges. Assorted colors. Standard 351 shape. Comes with pick holder. Essential accessory. Popular cross-sell item.'),
('Tambourine Half-Moon 10in', '8 pairs of steel jingles. Ergonomic grip handle. Synthetic head for consistent sound. Suitable for worship and classroom. Bright cutting tone. Durable construction.'),
('Microphone Pop Filter 6in', 'Double-layer nylon mesh. Gooseneck clamp adjusts to any position. Fits mic stands up to 1.5 inches. Reduces plosive sounds in vocal recording. Studio essential.'),
('Guitar Strap Adjustable Leather', 'Full-grain leather. Adjustable 42 to 56 inches. 2.5-inch width for comfort. Pick holder built in. Suitable for acoustic and electric guitars. Available in brown and black.'),
('Piano Key Cleaner Solution', 'Non-toxic formula safe for all key materials. 4oz spray bottle with microfiber cloth. Removes oils and grime. Does not damage ivory or plastic keys. Professional grade.'),
('Kazoo Metal Assorted 4-Pack', 'Anodized aluminum construction. Bright and buzzy tone. Replacement membranes included. Available in gold, silver, red, and blue. Popular party and classroom item.'),
('Thumb Piano Kalimba 17-Key', 'Mahogany body with warm resonance. Engraved note letters on tines. Includes tuning hammer and case. Stickers for beginners. Soothing and meditative tone.'),
('Drumpad Practice 12-Inch', 'Realistic bounce simulates snare feel. Non-slip rubber base. Quiet for apartment practice. 8mm threaded insert fits standard stands. Dual-surface for rim practice.'),
('Sheet Music Binder 9.5x12', '40 clear sleeves hold 80 pages. D-ring mechanism allows page turning. Concert-black exterior. Lay-flat design on music stand. Standard letter size sheets fit.'),
('Garden Hose Expandable 50ft', 'Expands to 3x length under water pressure. Latex core with polyester cover. Brass fittings resist corrosion. 8-pattern spray nozzle included. Stores compactly when drained.'),
('Pruning Shears Bypass', 'SK5 carbon steel blade. Bypass cutting action for clean cuts on live branches. Cuts stems up to 3/4 inch. Sap groove prevents sticking. Safety lock when closed.'),
('Raised Garden Bed 4x4ft', 'Cedar wood resists rot naturally. 11 inches deep for root vegetables. Tool-free assembly with corner brackets. No liner needed. Untreated wood is food-safe.'),
('Potting Soil Organic 16qt', 'OMRI listed for organic use. Peat moss, perlite, and compost blend. pH balanced for most plants. Feeds plants for up to 3 months. Moisture-retaining formula.'),
('Garden Gloves Thorn-Proof', 'Goatskin leather palms and fingers. Gauntlet cuff protects forearms. Reinforced fingertips. Suitable for rose bushes and blackberry. Available in S, M, L. Hand wash only.'),
('Seed Starting Tray 72-Cell', 'Reusable BPA-free plastic. Clear humidity dome retains moisture. Bottom drainage holes. Fits standard 10x20 trays. Label sticks included. Ideal for indoor seed starting.'),
('Soaker Hose 50ft Flat', 'Drip irrigation along entire length. Conserves water compared to sprinklers. UV-resistant cover. Connect multiple hoses end to end. Ideal for garden beds and hedgerows.'),
('Plant Labels Bamboo 50-Pack', '6-inch stakes write with permanent marker. Natural bamboo is eco-friendly. T-shape top for flat writing surface. Reusable season after season. Biodegradable at end of life.'),
('Compost Tumbler 37-Gallon', 'Dual-chamber design allows continuous composting. BPA-free recycled plastic. Internal aeration fins. Rodent-resistant sealed design. Produces compost in 4-6 weeks.'),
('Garden Kneeler Pad', 'High-density foam cushion. 18x11x1.5 inches. Waterproof and washable. Lightweight and portable. Also works as seat cushion. Carrying handle on side.'),
('Bird Feeder Squirrel-Proof', 'Weight-activated perch closes ports when squirrel sits. Holds 3 lbs of seed. UV-resistant polycarbonate tube. Easy-fill cap. Attracts cardinals, finches, and chickadees.'),
('Sprinkler Oscillating Adjustable', 'Covers up to 3600 sq ft. 18 rubber nozzles resist clogging. Range and width adjustable. Fits standard garden hose. Stable sled base. Leak-free connector.'),
('Tomato Cage Heavy Duty 4pk', '42 inches tall. 3-ring design supports indeterminate varieties. Powder-coated steel resists rust. Folds flat for off-season storage. Green color blends with foliage.'),
('Weed Barrier Fabric 4x50ft', 'UV stabilized polypropylene. Allows water and nutrients through. Blocks sunlight to prevent weed growth. Overlap seams 6 inches. Secure with landscape staples.'),
('Rain Gauge Glass Outdoor', 'Measures up to 5 inches. Magnifying glass tube for easy reading. Galvanized steel bracket. Mounts on fence post or stake. Replacement tubes available.'),
('Garden Tool Set 3-Piece', 'Includes trowel, cultivator, and transplanter. Cast aluminum heads. Ergonomic rubber handles. Rust-resistant finish. Hanging holes for wall storage. Gift box packaging.'),
('Plant Pot Self-Watering 12in', 'Built-in reservoir supplies water for up to 2 weeks. Water level indicator visible. UV-resistant resin. Drainage plug for indoor/outdoor use. Modern matte finish.'),
('Neem Oil Concentrate 16oz', 'Organic pest and disease control. Dilute 2 tablespoons per gallon. Controls aphids, mites, and fungal diseases. Safe for edible plants. Cold-pressed pure neem.'),
('Landscape Edging Steel 40ft', '4-inch depth defines garden borders. 16-gauge steel with dark green finish. Includes 15 steel stakes. Bendable for curved designs. Connects end to end seamlessly.'),
('Greenhouse Mini 4-Tier', '27x19x63 inches fits on patio or balcony. Clear PVC cover with roll-up zipper door. 4 steel wire shelves. Easy assembly. Extends growing season. Anchoring ropes included.'),
('Building Blocks Magnetic 60pc', 'Strong magnets click together easily. Translucent colored tiles. Compatible with other magnetic tile brands. CPSIA certified non-toxic. STEM learning for ages 3 and up.'),
('Puzzle Jigsaw 1000 Piece', 'High-quality chipboard with linen finish. Pieces cut with precision for snug fit. Finished size 27x20 inches. Reference poster included. Resealable bag for storage.'),
('Remote Control Car Off-Road', '2.4GHz controller range up to 80 meters. 4WD with independent suspension. Rechargeable battery runs 25 minutes. Rubber tires grip all surfaces. Ages 8 and up.'),
('Play-Doh Set 10-Pack Colors', 'Non-toxic and safe for children. 2oz cans in assorted colors. Colors can be mixed. Reusable if stored in sealed cans. Classic toy with strong brand recognition.'),
('Science Kit Crystal Growing', 'Grow 5 real crystals in different colors. Includes all materials and display domes. Results visible in 7 days. Educational guide explains crystal formation. Ages 10 and up.'),
('Board Game Strategy Family', '2-4 players, ages 10 and up. Average game time 45 minutes. Tile-placement mechanic. High replay value. Award-winning design. Instructions in 6 languages.'),
('Stuffed Animal Plush Bear 18in', 'Ultra-soft polyester plush. Embroidered eyes for safety. Machine washable and dryer safe. Meets ASTM F963 safety standards. All ages. Popular gift item year-round.'),
('Marble Run Set 120 Pieces', 'Translucent track pieces. Compatible with standard 15mm marbles. Includes 20 glass marbles. Encourages engineering thinking. Ages 4 and up. Instruction booklet with 5 designs.'),
('Bubble Machine Automatic', 'Produces 800 bubbles per minute. Battery operated with 4 AA. Includes 8oz bubble solution. Lightweight for small hands. Indoor and outdoor use. Replacement solution available.'),
('Card Game Family Quick Play', '2-6 players. Game rounds last 15 minutes. Simple rules for ages 7 and up. 108 cards included. Travel-friendly tin case. High replayability with random card draws.'),
('Toy Dinosaur Set 12-Pack', 'Hand-painted realistic figures. Includes T-Rex, Triceratops, and Stegosaurus among others. Average size 7 inches. Non-toxic PVC material. Educational name labels included.'),
('Kite Diamond Classic 48in', 'Ripstop nylon sail. Fiberglass frame. 200-foot string on winder included. Flies in winds 6-20 mph. Assembly takes 5 minutes. Bright rainbow design visible at height.'),
('Kinetic Sand 2lb Bag', 'Flows through fingers like wet sand. Never dries out. 98% sand, 2% magic. Hypoallergenic and gluten-free. Easy cleanup. Available in natural and colored options.'),
('Toy Kitchen Playset 30pc', 'Includes pots, pans, utensils, and play food. Bright colors attract toddlers. Fits in play kitchen sets. BPA-free plastic. Dishwasher safe. Ages 3 and up.'),
('Robot Building Kit STEM', '249 pieces build 3 different robot designs. App-controlled via Bluetooth. Programmable movements and sounds. Ages 8 and up. Rechargeable battery. Develops coding skills.'),
('Wooden Train Set 50-Piece', 'Compatible with all major wooden track brands. Includes engine, cars, bridge, and trees. Non-toxic paint. Smooth edges safe for toddlers. Ages 2 and up.'),
('Toy Telescope Kids 20x', '20x magnification. Tabletop tripod included. 2 eyepieces for different magnifications. Moon filter for comfortable lunar viewing. Instruction guide with star map. Ages 6 and up.'),
('Water Gun Super Soaker', 'Holds 40oz of water. Pump-action shoots up to 35 feet. No batteries required. Durable ABS plastic. Easy-fill cap. Ages 6 and up. Popular summer seasonal item.'),
('Coding Game Board for Kids', 'No screen or app required. Teaches programming logic with physical tiles. 120 challenge cards in progressive difficulty. Ages 4-10. Award-winning STEM toy.'),
('Dollhouse Wooden 3-Story', '28 inches tall with 5 rooms. Includes 15 furniture pieces. Compatible with 6-inch dolls. Wood and MDF construction. Easy assembly with illustrated instructions. Ages 3 and up.'),
('Cookbook Plant-Based Meals', '150 recipes with nutritional information. Full-color photography for every dish. Spiral binding lies flat on counter. Seasonal ingredient guide. Dietary tags for gluten-free and nut-free.'),
('Journal Leather Bound Blank', '240 pages of acid-free cream paper. Genuine leather cover with wrap closure. Lay-flat binding. Ribbon bookmark. 5.5x8 inch size. Popular gift for writers and travelers.'),
('Planner Weekly Undated 12-Mo', 'Undated format starts any time. Weekly and monthly views. Goal-setting pages. Habit tracker. Thick 120gsm paper prevents bleed-through. Elastic closure and back pocket.'),
('Coloring Book Adult Mandala', '50 single-sided designs. Perforated pages for easy removal. Printed on heavyweight paper. Suitable for markers and colored pencils. Stress-relieving patterns. Bestseller in category.'),
('Notebook Dot Grid A5', '192 pages of 120gsm ivory paper. 5mm dot grid spacing. Numbered pages with index. Lay-flat stitched binding. Hard cover with elastic closure. Fountain pen friendly.'),
('Flashcards Language Spanish', '1000 cards with common words and phrases. Color-coded by category. Pronunciation guide on each card. Ring-bound for portability. Suitable for beginners and intermediate learners.'),
('Book Stand Adjustable Reading', 'Holds books up to 3 inches thick. 7 angle adjustments. Weighted base prevents tipping. Page clips hold position. Works for textbooks, tablets, and cookbooks. Folds flat.'),
('Graph Paper Pad Engineering', '100 sheets of 1/4-inch grid. 8.5x11 inches. 20lb paper suitable for pencil. Top-bound with chipboard back. Green grid lines. Standard for engineering calculations.'),
('Dictionary Pocket Paperback', '40000 entries with pronunciation guides. Compact 4x6 inch size. Updated edition with modern terms. Lightweight for backpack. Clear typeface. Thumb index tabs.'),
('Sticky Notes Variety 24-Pack', '12 colors in 3x3 inch size. 100 sheets per pad. Strong adhesive stays put. Clean removal without residue. Bulk pack for office supply. Recyclable paper.'),
('Atlas World Geographic Large', 'Detailed political and physical maps. Country profiles with population and GDP data. 12x15 inch large format. Updated national boundaries. Climate and terrain maps included.'),
('Sketchpad Toned Tan 9x12', '80 sheets of tan-toned paper. Highlights pop with white pencil. 80lb weight handles mixed media. Wire-bound. Acid-free for archival work. Popular with portrait artists.'),
('Bookmark Magnetic Set 12pc', 'Folds over page edge. Does not slip out. Assorted literary quote designs. Thin profile does not bulk book. Makes great small gift. Packaged in display box.'),
('Workbook Math Grade 3', 'Aligned with Common Core standards. 200 practice pages. Answer key in back. Covers multiplication, fractions, and geometry basics. Perforated pages. Parent guide included.'),
('Recipe Binder Kit Blank', '52 blank recipe cards 4x6 inches. Tabbed dividers by meal type. 3-ring binder with wipe-clean cover. Sheet protectors for messy kitchens. Family heirloom quality.'),
('Wall Clock Modern 12-Inch', 'Silent sweep movement. Large numbers easy to read. Battery operated with AA. Aluminum frame. Available in black, white, and rose gold. No ticking noise.'),
('Picture Frame Set 7-Piece', 'Assorted sizes from 4x6 to 8x10. Gallery wall template included. Real glass fronts. Sawtooth and easel back. Matte white wood finish. Hanging hardware included.'),
('Candle Soy Scented 3-Pack', 'Hand-poured soy wax. 45-hour burn time each. Cotton wicks for clean burn. Scents: vanilla, lavender, and cedar. 8oz glass jars reusable. Gift box packaging.'),
('Throw Blanket Knit Cotton', '100% organic cotton. 50x60 inches. Machine washable. Waffle weave texture. Available in oatmeal, gray, and sage. Decorative fringe edges. Hypoallergenic.'),
('Vase Ceramic Modern 10-Inch', 'Matte finish in neutral tones. Narrow neck for single stems or small bouquets. Waterproof glazed interior. Hand wash only. Weighted base prevents tipping.'),
('Floating Shelf Wood 24-Inch', 'Solid pine with walnut stain. Hidden bracket mounting. Supports up to 25 lbs. Hardware and template included. 24x6x1.5 inches. Smooth sanded finish.'),
('Mirror Round Wall 24-Inch', 'Aluminum alloy frame. Available in gold, black, and brass. Shatter-proof construction. D-ring hanging hardware. Suitable for bathroom, entry, or living room.'),
('Plant Stand Indoor Metal', 'Mid-century modern design. Holds pots up to 10 inches diameter. 10-inch height. Powder-coated steel. Rubber feet protect floors. Available in black, white, and gold.'),
('Cushion Cover Linen 18x18 2pk', '55% linen, 45% cotton blend. Hidden zipper closure. Machine washable. Insert not included. Available in 12 earth-tone colors. Minimalist textured design.'),
('LED String Lights 33ft', '100 warm white LEDs. Copper wire is flexible and shapeable. USB powered with 8 modes. Waterproof for indoor and outdoor. Timer function. Low heat emission.'),
('Diffuser Essential Oil Reed', 'Natural rattan reeds absorb and disperse scent. 4oz glass bottle. Lasts 2-3 months. Available in eucalyptus, bergamot, and sandalwood. No flame needed. Safe around pets.'),
('Wall Art Canvas Abstract 3pc', 'Gallery-wrapped canvas set. Each panel 12x16 inches. Ready to hang with hardware. Giclee print on cotton canvas. UV-resistant inks. Modern abstract design.'),
('Rug Bath Memory Foam 20x30', '1-inch thick memory foam core. Microfiber top is soft underfoot. Non-slip TPR backing. Machine washable. Quick-drying. Available in 8 colors.'),
('Tray Decorative Wood Round', 'Mango wood with metal handles. 14-inch diameter. Hand-carved detail. Suitable for ottoman or coffee table styling. Food-safe finish. Each piece slightly unique.'),
('Coaster Set Marble 4-Pack', 'Natural marble with cork backing. 4-inch diameter. Absorbent and heat resistant. Each coaster has unique veining. Holder included. Gift-ready packaging.'),
('Curtain Sheer White 84-Inch', 'Rod pocket and back tab hanging options. 52x84 inches per panel. Sold individually. Light filtering while maintaining privacy. Machine washable. Wrinkle-resistant polyester.'),
('Desk Clock Small Analog', '3-inch diameter. Silent quartz movement. Battery operated. Aluminum frame. Modern minimalist design. Ideal for nightstand or desk. Available in matte black and silver.'),
('Garland Eucalyptus Faux 6ft', 'Realistic plastic and fabric leaves. Wire stem bends to shape. UV resistant for outdoor mantle use. No water needed. Can be cut to desired length.'),
('Door Mat Coir Natural 18x30', 'Natural coconut fiber scrapes shoes clean. PVC backing prevents slipping. 1-inch thick pile. Weather resistant. Shake or vacuum to clean. Classic design.'),
('Serving Board Acacia Wood', '16x8 inch live-edge board. Food-safe mineral oil finish. Includes leather hanging strap. Each board has unique wood grain. Hand wash and oil periodically.'),
('Microfiber Cloth Set 12-Pack', 'Ultra-absorbent 300GSM. Lint-free cleaning. 16x16 inch size. Machine washable 500 times. Suitable for glass, screens, and countertops. Color-coded for different rooms.'),
('Spray Bottle Glass 16oz 2pk', 'Amber glass blocks UV light. Fine mist and stream settings. Silicone sleeve protects from drops. Suitable for DIY cleaning solutions. BPA-free trigger sprayer.'),
('Scrub Brush Bamboo Handle', 'Stiff sisal bristles for tough jobs. 10-inch bamboo handle. Hanging loop for storage. Suitable for pots, pans, and grout. Biodegradable materials. Replaces plastic brushes.'),
('Lint Roller Extra Sticky 5pk', '60 sheets per roll with 5 roll refills. Tears cleanly from roll. Works on clothing, upholstery, and car seats. Ergonomic handle. Removes pet hair effectively.'),
('Dusting Wand Extendable', 'Extends from 30 to 54 inches. Chenille microfiber head attracts dust. Flexible head bends to reach ceiling fans. Machine washable head. Telescoping aluminum handle.'),
('Sponge Cellulose Natural 6-Pack', 'Plant-based cellulose. Biodegradable and compostable. Absorbs 20x its weight in water. Durable for weeks of use. No synthetic materials. Rinse and air dry between uses.'),
('Toilet Brush Silicone', 'Flexible silicone bristles resist bacteria. Quick-drying design. Slim holder fits beside toilet. Wall-mountable. Hygienic alternative to traditional bristle brushes. Replacement head available.'),
('Mop Spray Microfiber Flat', 'Built-in spray trigger dispenses solution. Washable microfiber pad included. 360-degree swivel head. Lightweight design. Suitable for hardwood, tile, and laminate. Refillable 20oz tank.'),
('Squeegee Window Professional', '14-inch stainless steel channel. Replaceable rubber blade. Ergonomic handle. Streak-free finish on glass. Extension pole compatible. Used by professional cleaners.'),
('Dish Brush Palm Wood', 'Natural tampico fiber bristles. Palm wood handle is biodegradable. Comfortable grip shape. Bristles are heat resistant. Replacement heads available. Zero-waste kitchen essential.'),
('Vacuum Bags HEPA 6-Pack', 'Compatible with Miele Classic C1 series. HEPA filtration captures 99.97% of particles. Auto-seal closure when removed. Each bag holds 3.5 liters. Genuine replacement part.'),
('Broom Angle Cut Indoor', 'Flagged bristle tips sweep fine particles. 55-inch handle. Lightweight at 1.5 lbs. Hang-up hole. Bristles made from recycled PET bottles. 12-inch wide sweep head.'),
('Drain Snake Hair Clog 5pk', '20-inch flexible plastic strip. Barbed edges grab hair and debris. Disposable after use. No chemicals needed. Fits standard drains. Easy DIY plumbing solution.'),
('Dishwasher Pods Eco 60ct', 'Plant-based formula. No phosphates or chlorine. Individually wrapped dissolvable film. Cuts grease effectively. Septic safe. Fragrance-free option for sensitive noses.'),
('Trash Bags Drawstring 13gal 90ct', '1.2 mil thickness resists punctures. Drawstring closure for easy carry. Fits standard kitchen cans. Unscented. Custom fit design stretches to fit. Flex technology.'),
('Hair Dryer Ionic Compact', '1875W motor with ceramic technology. 3 heat and 2 speed settings. Ionic conditioning reduces frizz. Concentrator and diffuser nozzles included. Foldable handle for travel.'),
('Makeup Brush Set 12pc', 'Synthetic taklon bristles. Includes foundation, powder, contour, and eye brushes. Vegan and cruelty-free. Rose gold ferrules. Faux leather roll case. Soft bristles wash easily.'),
('Nail Clipper Set Stainless 3pc', 'Includes fingernail, toenail, and precision clippers. Surgical-grade stainless steel. Sharp curved blades for clean cut. Swing-out nail file. Zippered leather case.'),
('Face Moisturizer SPF 30', 'Broad-spectrum UVA/UVB protection. Lightweight non-greasy formula. Suitable for daily use under makeup. Fragrance-free and non-comedogenic. 2oz tube. Dermatologist tested.'),
('Electric Toothbrush Sonic', '31000 brush strokes per minute. 2-minute smart timer with 30-second intervals. 3 cleaning modes. USB-C rechargeable lasting 30 days. 2 replacement heads included.'),
('Hair Trimmer Precision', '0.5mm to 10mm cutting length. Stainless steel blade. Cordless with 90-minute runtime. IPX7 waterproof for shower use. Includes 4 guide combs. USB-C charging.'),
('Makeup Mirror LED Lighted', '1X and 10X magnification sides. 36 LED lights simulate daylight. Touch dimmer control. Rechargeable battery lasts 2 weeks. Swivel base. Satin nickel finish.'),
('Lip Balm Organic 4-Pack', 'USDA organic beeswax formula. Flavors: mint, vanilla, honey, and unscented. SPF 15 sun protection. No petroleum or parabens. Moisturizes for 4 hours. Recyclable tubes.'),
('Facial Cleansing Brush Silicone', 'Medical-grade silicone bristles. 8000 vibrations per minute. Waterproof IPX7. USB rechargeable lasts 300 uses. Gentle on sensitive skin. Replaces disposable cleansing pads.'),
('Essential Oil Set 6-Pack', 'Includes lavender, peppermint, eucalyptus, tea tree, orange, and lemongrass. 10ml bottles. 100% pure therapeutic grade. GC/MS tested for purity. Dropper caps included.'),
('Beard Oil Natural 2oz', 'Jojoba and argan oil base. Cedar and sandalwood scent. Softens and conditions beard hair. Reduces itch and flaking. Glass dropper bottle. Small-batch production.'),
('Exfoliating Gloves Pair 4pk', 'Nylon mesh texture. Stimulates circulation while removing dead skin. Quick-drying material. Machine washable. Available in neutral colors. Unisex one-size-fits-most.'),
('Cotton Rounds Organic 100ct', '100% organic cotton. Biodegradable and compostable. Soft texture for toner and makeup removal. Lint-free surface. Chemical-free processing. Resealable packaging.'),
('Tweezers Precision Slant Tip', 'Hand-filed slant tip grabs finest hairs. Stainless steel with satin finish. Aligned tips tested individually. Calibrated tension for control. Protective sleeve included.'),
('Scalp Massager Shampoo Brush', 'Soft silicone bristles. Stimulates blood flow to follicles. Waterproof for shower use. Ergonomic palm grip. Distributes shampoo evenly. Suitable for all hair types.'),
('Basketball Indoor Outdoor 29.5', 'Composite leather cover. Official size 7. Deep channel design for grip. Butyl bladder retains air. Suitable for concrete and hardwood. Comes fully inflated.'),
('Tennis Balls Can of 3', 'ITF approved for tournament play. Pressurized felt cover. Consistent bounce. Dura-weave felt for longer life. Resealable can. Also used for dog fetch and physical therapy.'),
('Swim Goggles Anti-Fog', 'Silicone gasket seals comfortably. UV protection rated. Anti-fog coated lenses. Adjustable split strap. Available in clear, blue, and smoke tints. Fits adult faces.'),
('Soccer Ball Size 5', 'Machine-stitched TPU panels. Official size and weight for ages 12 and up. Butyl bladder. All-weather surface. Printed team logos available for custom orders. FIFA inspected.'),
('Yoga Strap Cotton 8ft', 'D-ring buckle closure. 1.5-inch width comfortable on body. 100% cotton will not stretch. Extends reach in poses. Machine washable. Available in 5 colors.'),
('Badminton Set 4-Player', 'Includes 4 rackets, 3 shuttlecocks, and net with poles. Steel shaft rackets. Carrying case. Sets up in 10 minutes. Great for backyard and beach. Family activity.'),
('Golf Balls Practice Foam 24pk', 'Limited-flight foam construction. Safe for indoor and backyard practice. Realistic feel on impact. 70% flight distance of real ball. Will not damage windows or walls.'),
('Skateboard Complete 31-Inch', '7-ply maple deck. 5.25 inch aluminum trucks. ABEC-7 bearings. 52mm 95A PU wheels. Ready to ride. Graphic design on bottom. Weight capacity 220 lbs.'),
('Table Tennis Paddle Set', '2 paddles and 3 balls included. 5-ply blade for control. Pips-in rubber for spin. Flared handle for comfort. Suitable for recreational and intermediate play. Carrying case.'),
('Running Belt Waist Pack', 'Fits phones up to 6.7 inches. Bounce-free design. Reflective trim for night runs. Adjustable elastic waist 26-40 inches. Headphone port. Water-resistant zipper.'),
('Lacrosse Ball Massage 2-Pack', 'Solid natural rubber. 2.5 inch diameter. Dense enough for trigger point massage. Used by athletes and physical therapists. Will not lose shape over time.'),
('Cricket Bat Tennis Ball Grade', 'Kashmir willow blade. Full-size short handle. Ideal for tennis ball cricket. Lightweight at 2.2 lbs. Grip pre-installed. Entry-level bat for casual play.'),
('Volleyball Official Size', '18-panel machine-stitched design. Soft touch synthetic leather. Official size and weight. Indoor and outdoor use. Butyl bladder holds air. Visible in bright white and blue.'),
('Ski Wax Universal 5oz', 'All-temperature formula for -30 to 30 degrees F. Rub-on application requires no iron. Suitable for skis and snowboards. Fluorocarbon-free eco formula. Zip pouch for travel.'),
('Disc Golf Putter Driver 3pk', 'Includes putter, midrange, and driver. 170-175 gram weights. Suitable for beginners. Different plastics for grip and durability. PDGA approved. Course-ready set.'),
('Sleeping Bag 3-Season', 'Comfort rating 20 degrees F. Hollow fiber fill. Mummy shape with hood. Full-length two-way zipper. Compression sack included. Total weight 3.5 lbs. Machine washable.'),
('Tent 2-Person Backpacking', 'Freestanding dome design. 2 doors and 2 vestibules. Fly rated 1500mm waterproof. 4.5 lbs packed weight. Sets up in 5 minutes. Aluminum poles. Footprint sold separately.'),
('Camp Pillow Inflatable', 'Packs to size of soda can. Weighs 2.7 ounces. Soft brushed fabric top. Ergonomic cradle design. Inflation valve requires 3 breaths. Stuff sack doubles as pillowcase.'),
('Cooking Utensil Set Camp', 'Includes spatula, ladle, tongs, and serving spoon. Heat-resistant nylon. Carabiner clip connects set. BPA-free. Lightweight at 3.5 ounces total. Fits in cook kit.'),
('Water Bottle Collapsible 1L', 'BPA-free silicone. Rolls up when empty. Carabiner cap clips to pack. Wide mouth for ice cubes. Dishwasher safe. Available in 4 colors. Tastes and smell neutral.'),
('First Aid Kit Wilderness', '85 pieces including trauma supplies. Moleskin for blisters. SAM splint for fractures. Organized in clear pouches. Waterproof nylon case. Compact 6x8 inches. 12oz total weight.'),
('Bear Canister Food Storage', 'BPA-free polycarbonate. Capacity 615 cubic inches. IGBC certified for all bear areas. Transparent to see contents. Weighs 2.1 lbs empty. Doubles as camp seat.'),
('Camp Shower Solar 5-Gallon', 'Black PVC absorbs solar heat. Reaches 113 degrees in 3 hours. Shower head with on/off valve. Rope handle for hanging. Folds flat when empty. Gravity-fed pressure.'),
('Sleeping Pad Inflatable', 'R-value 4.0 for three-season use. 2.5 inches thick when inflated. 20-denier ripstop nylon. Weighs 16 ounces. Stuff sack and repair kit included. Inflate in 10-15 breaths.'),
('Headnet Mosquito Protection', 'Fine 1200-hole mesh blocks no-see-ums. Fits over any hat brim. Elastic hem seals at neck. Weighs 0.7 ounces. Compact storage. Essential for buggy campsites.'),
('Fire Pit Portable Folding', 'Stainless steel construction. 14-inch diameter. Folds flat to 1-inch profile. Legs elevate fire from ground. Carry bag included. Leave-no-trace camping compliant.'),
('Camp Chair Heavy Duty 500lb', 'Oversized seat 25 inches wide. Rated to 500 lbs. Steel frame with reinforced joints. Cup holder and side pocket. Carry bag with shoulder strap. 12 lbs packed weight.'),
('Parachute Cord 100ft 550', 'Type III 550 paracord. 7 inner strands. Nylon sheath. Tensile strength 550 lbs. Multiple uses: shelter, repair, clothesline. Made in USA. Available in 20 colors.'),
('Camp Towel Quick-Dry', 'Microfiber absorbs 4x its weight. Dries 10x faster than cotton. 30x60 inch size. Snap loop for hanging. Mesh carry bag. Antibacterial treatment. Lightweight at 9 ounces.'),
('Firestarter Tinder Cubes 20pk', 'Burns 8 minutes each. Lights with single match even when wet. Non-toxic paraffin wax. Individually wrapped. Odorless when stored. Works at any altitude.'),
('Camera Strap Leather', 'Full-grain leather with brass hardware. Adjustable 38 to 52 inches. Compatible with all cameras with standard lugs. Shoulder pad for heavy setups. Ages beautifully with use.'),
('Tripod Travel Carbon Fiber', '5-section legs extend to 60 inches. Folds to 14 inches. Ball head with 360-degree panning. Weighs 2.4 lbs. Load capacity 22 lbs. Quick-release plate included.'),
('Memory Card SD 64GB V30', 'Read speed 170MB/s, write 90MB/s. V30 video speed class. 4K UHD recording capable. Water, shock, and X-ray proof. Includes full-size SD adapter. 10-year warranty.'),
('Lens Cleaning Kit 5-in-1', 'Includes blower, brush, cleaning fluid, microfiber cloths, and lens tissue. Fits in camera bag pocket. Safe for coated optics. Also works for binoculars and telescopes.'),
('Camera Bag Sling Shoulder', 'Fits mirrorless camera with 2 lenses. Quick-access side opening. Tablet sleeve fits up to 10 inches. Rain cover in bottom pocket. Padded dividers adjustable.'),
('ND Filter Set 67mm 3-Pack', 'Includes ND4, ND8, and ND16 filters. Multi-coated optical glass. Slim profile prevents vignetting. Reduces light for long exposures. Protective case for storage.'),
('Phone Lens Kit Clip-On 3pc', 'Wide-angle, macro, and fisheye lenses. Universal clip fits all phones. Multi-element glass optics. Carrying case included. Great for mobile photography hobbyists.'),
('Light Box Photo Studio 16in', '60 LED lights with adjustable brightness. 4 colored backdrops included. Folds flat for storage. USB powered. Diffused lighting eliminates harsh shadows. Product photography essential.'),
('Camera Remote Shutter Wireless', 'Bluetooth range up to 30 feet. Compatible with iOS and Android cameras. CR2032 battery lasts 1 year. Keychain size. Perfect for group photos and selfies.'),
('Film 35mm Color 3-Pack', 'ISO 400 versatile speed. 36 exposures per roll. Fine grain for enlargements. Daylight balanced. Process C-41 at any photo lab. Archival storage recommended.'),
('Drone Landing Pad 30-Inch', 'Foldable waterproof surface. High-visibility orange and blue sides. 4 ground stakes anchor in wind. Fits in drone bag. Protects gimbal during takeoff and landing.'),
('Monitor Calibrator Color', 'Hardware calibration for accurate color. Supports LCD, LED, and OLED monitors. Ambient light sensor adjusts profile. Software for Mac and Windows. Profiles save automatically.'),
('Gimbal Stabilizer Smartphone', '3-axis motorized stabilization. Foldable design fits in pocket. Object tracking via app. Time-lapse and panorama modes. Battery lasts 8 hours. Tripod base included.'),
('Photo Album Self-Adhesive 60pg', 'Magnetic self-adhesive pages. Holds up to 360 4x6 photos. Leather cover with window. Acid-free pages protect photos. Lay-flat binding. Comes in gift box.'),
('Reflector 5-in-1 Collapsible 32in', 'Silver, gold, white, black, and translucent surfaces. Collapses to 12 inches. Zippered carry case. Essential for portrait and product photography. Sturdy steel frame.'),
('Sewing Kit Travel Compact', 'Over 100 pieces. Includes needles, threads in 24 colors, scissors, and buttons. Zippered PU leather case. Mending solution for emergencies. Suitable for beginners.'),
('Embroidery Hoop Set 5pc', 'Bamboo hoops in 4, 6, 7, 8, and 10 inch diameters. Brass adjustment screw. Smooth interior prevents fabric snagging. Suitable for cross-stitch and embroidery.'),
('Hot Glue Gun Cordless', 'Heats in 60 seconds. Runs on lithium battery for 45 minutes. Drip-free nozzle. Includes 20 glue sticks. LED light illuminates work area. Safety stand prevents tipping.'),
('Cutting Mat Self-Healing 18x24', '5-layer PVC construction. Printed grid with 1-inch and 1/8-inch lines. Angle guides at 30, 45, and 60 degrees. Self-healing surface lasts years. Non-slip bottom.'),
('Rotary Cutter 45mm', 'Tungsten steel blade for precision cutting. Ergonomic soft grip. Blade guard for safety. Compatible with straight rulers and templates. Cuts fabric, paper, and vinyl.'),
('Yarn Skein Acrylic 3-Pack', 'Worsted weight #4. 364 yards per skein. Machine washable and dryable. Low-pill formula. Available in 40 colors. Suitable for knitting and crochet. Soft hand feel.'),
('Knitting Needles Set Bamboo', '18 pairs in US sizes 0-15. Natural bamboo is warm to touch and lightweight. Needle gauge and stitch markers included. Fabric case with labeled pockets.'),
('Stamp Set Rubber Alphabet', '26 uppercase and 26 lowercase letters plus numbers. Wooden handles. 3/4-inch character height. Works with any ink pad. Organized in wooden tray. Hand-cut rubber.'),
('Beading Kit Jewelry Making', 'Over 2000 beads in assorted colors and shapes. Includes elastic cord, clasps, and pliers. Organized in compartmented case. Instructions for 10 bracelet designs.'),
('Fabric Scissors 8-Inch', 'Stainless steel micro-serrated blade grips fabric. Bent handle for flat cutting on table. Comfortable molded grip. Cuts multiple layers cleanly. Right-hand design.'),
('Paint Palette Porcelain', '10-well design with large mixing area. Glazed surface cleans easily. 9-inch diameter. Does not stain like plastic. Heavy enough to stay put. Works with all water-based paints.'),
('Decoupage Glue Matte 16oz', 'All-in-one sealer, glue, and finish. Matte finish dries clear. Non-toxic water-based formula. Suitable for paper, fabric, and napkins on wood and glass surfaces.'),
('Leather Craft Tool Kit 18pc', 'Includes stitching groover, edge beveler, hole punch, needles, and waxed thread. Organized in zippered pouch. Beginner-friendly instruction guide. Quality steel tools.'),
('Resin Epoxy Clear 16oz Kit', '2-part mix cures crystal clear. Low odor formula. Self-leveling. UV resistant to prevent yellowing. Cures in 24 hours. Suitable for jewelry, coasters, and art.'),
('Stencil Set Reusable 20pc', 'Mylar plastic withstands repeated use. Assorted patterns: geometric, floral, and border. 6x6 inch size. Works with paint, ink, and airbrush. Wash and reuse indefinitely.'),
('Stapler Desktop Heavy Duty', 'Staples up to 100 sheets. Uses standard and heavy-duty staples. All-metal construction. Adjustable paper guide. Non-slip rubber base. Jam-free mechanism. Includes 1000 staples.'),
('Paper Shredder Cross-Cut', 'Shreds 12 sheets at a time. Cross-cut produces P-4 security level particles. 5-gallon bin. Auto-start and reverse. Shreds credit cards and CDs. Overload indicator light.'),
('Label Maker Handheld', 'QWERTY keyboard. 6 font sizes and 8 styles. Multiple tape widths from 6mm to 12mm. Prints barcodes and symbols. Battery or AC powered. Preview screen before printing.'),
('Whiteboard Markers Fine 12pk', 'Fine tip for detailed writing. 12 vibrant colors. Low-odor formula. Cap indicates color. Erases cleanly from whiteboards. Does not bleed through paper.'),
('Desk Drawer Organizer Bamboo', '5-compartment expandable design. Fits standard desk drawers. Natural bamboo construction. Adjustable dividers. Holds pens, clips, and sticky notes. Non-slip feet.'),
('Paper Clips Jumbo 100ct', '2-inch size holds thick document stacks. Smooth finish does not snag paper. Corrosion-resistant steel. Reclosable box packaging. Standard office supply item. Low-cost high-volume.'),
('Desk Name Plate Holder', 'Aluminum frame with clear insert. 8x2 inches. Double-sided printing visible from both directions. Includes blank insert cards. Suitable for offices, lobbies, and conferences.'),
('Letter Tray Stackable 3-Tier', 'Mesh steel construction in black. Each tier 13x10x3 inches. Stacks vertically to save desk space. Organizes mail, documents, and folders. Rubber feet protect desk.'),
('Binder Clips Assorted 48pc', 'Includes small, medium, and large sizes. Steel wire handles fold flat. Strong clamping force. Reusable. Comes in dispenser tub. Essential for document organization.'),
('Correction Tape Runner 6-Pack', '5mm width covers single lines cleanly. Instant dry for immediate writing. 33 feet per cartridge. Ergonomic body shape. Writes over smoothly with pen or pencil.'),
('Envelope Moistener Sponge', 'Eliminates licking envelopes. Clean and hygienic. Sponge tip applies even moisture. Bottle holds 2oz of water. Durable construction lasts years. Office mail room essential.'),
('Push Pins Clear 200ct', 'Transparent plastic heads blend with surfaces. Sharp steel points. Head diameter 10mm. Standard length for cork boards. Bulk packaging for office supply rooms.'),
('Rubber Bands Assorted 1lb', 'Natural rubber. Assorted sizes 10 to 64. 1-lb box approximately 400 bands. Will not dry out or snap easily. Standard office supply. Store away from heat and light.'),
('Scissors Office 8-Inch', 'Stainless steel blades stay sharp. Comfort-grip handles. Suitable for paper, cardboard, and tape. Ambidextrous design. Lifetime warranty. Blade length 3.5 inches.'),
('Tape Dispenser Weighted Desktop', 'Non-skid weighted base stays in place. Holds standard 3/4-inch rolls. One-hand operation. Serrated blade cuts cleanly. Black or silver finish. Includes 1 roll of tape.'),
('Smoke Detector Battery 10-Year', 'Sealed lithium battery lasts entire unit life. Photoelectric sensor reduces false alarms. 85dB alarm. Test button for monthly checks. Mounts with screws or adhesive.'),
('Fire Extinguisher ABC 5lb', 'Rated 3-A:40-B:C. Fights wood, liquid, and electrical fires. Metal head with gauge. Rechargeable by certified professional. Mounting bracket included. OSHA compliant.'),
('Carbon Monoxide Detector Digital', 'Digital display shows CO level. Battery backup during power outage. Electrochemical sensor for accuracy. 85dB alarm. End-of-life warning after 7 years. UL 2034 listed.'),
('First Aid Kit 300-Piece', 'Organized in compartmented hard case. Includes bandages, gauze, antiseptic, cold pack, and emergency blanket. First aid guide booklet. OSHA and ANSI compliant. Wall mountable.'),
('Door Stopper Security Alarm', '120dB alarm when door is pushed against stopper. Non-skid rubber pad. Battery operated. Travel security essential. Works on carpet and hard floors. No installation needed.'),
('Safe Lock Box Fireproof', '30-minute fire protection at 1550 degrees F. Digital keypad with key backup. Interior 0.17 cubic feet. Bolts to floor with included hardware. Stores documents and valuables.'),
('Emergency Radio Hand Crank', 'AM/FM/NOAA weather channels. Hand crank, solar, and USB charging. Built-in flashlight and phone charger. SOS alarm. Compact and portable. Essential disaster preparedness item.'),
('Reflective Vest Safety 5-Pack', 'Hi-vis yellow-green color. 2-inch reflective strips front and back. One size adjustable with velcro. Meets ANSI/ISEA 107 Class 2. Lightweight and breathable mesh.'),
('Motion Sensor Light Battery', '14 LEDs activate on motion detection. Detection range 10 feet, 120 degrees. Auto shutoff after 15 seconds. Adhesive and screw mount options. Suitable for closets and stairs.'),
('Water Leak Detector WiFi', 'Sensor alerts phone immediately via app. 100dB local alarm. Extends detection with rope sensor sold separately. Battery lasts 2 years. Place near water heater and washing machine.'),
('Bottle Warmer Quick Heat', 'Heats breast milk and formula in 3 minutes. Fits all bottle sizes and brands. Auto shutoff prevents overheating. Keeps milk at ideal temperature. BPA-free steam system.'),
('Pacifier Silicone Orthodontic 4pk', 'Orthodontist-designed nipple shape. Medical-grade silicone. BPA and latex-free. Sterilizer case included. Available for ages 0-6 and 6-18 months. Easy to clean.'),
('Baby Monitor Audio Digital', 'DECT technology eliminates interference. 1000-foot range. Night light and lullaby function. Two-way talk-back. Low battery alert. Expandable to 4 cameras. Belt clip on parent unit.'),
('Diaper Bag Backpack', '16 pockets including insulated bottle pocket. Water-resistant nylon. Changing pad included. Stroller straps attach to handlebar. USB charging port. Unisex design in gray.'),
('Teething Toy Silicone Ring', '100% food-grade silicone. Multiple textures soothe sore gums. Refrigerator safe for cooling relief. Easy grip for small hands. BPA, PVC, and phthalate-free. Dishwasher safe.'),
('Swaddle Blanket Muslin 3-Pack', '100% organic cotton muslin. 47x47 inches. Breathable open weave. Pre-washed for softness. Gets softer with each wash. Versatile as blanket, nursing cover, or burp cloth.'),
('Baby Nail Trimmer Electric', 'Quiet motor does not wake sleeping baby. 4 filing pads for different ages. LED light for visibility. Battery operated. Safer than traditional clippers. Includes travel case.'),
('High Chair Portable Clip-On', 'Clamps to tables 1 to 3 inches thick. Supports up to 37 lbs. Folds flat with carry bag. Removable washable seat pad. Rubberized clamp grips prevent damage.'),
('White Noise Machine Baby', '6 soothing sounds including heartbeat. Timer options 15, 30, and 60 minutes. Compact clip-on attaches to crib or stroller. Rechargeable battery lasts 8 hours. Volume limiter for safety.'),
('Bath Thermometer Digital Duck', 'Floating duck design entertains baby. LCD screen shows water temperature. Alerts if water too hot. Waterproof. Battery included. Also displays room temperature. BPA-free.'),
('Packing Cubes Set 6-Piece', '3 sizes for clothing organization. Mesh top panel for visibility. Durable nylon with reinforced seams. Double zippers. Lightweight adds minimal weight. Available in 8 colors.'),
('Travel Pillow Memory Foam', '360-degree neck support. Washable velour cover. Snap closure keeps pillow in place. Compresses to half size. Carrying bag included. Does not inflate or deflate.'),
('Luggage Scale Digital 110lb', 'Accuracy within 0.1 lb. Large LCD display. Includes measuring tape. Auto-hold reading. Tare function. Battery indicator. Compact for packing in suitcase. Avoids overweight fees.'),
('Toiletry Bag Hanging Organizer', 'Multiple compartments and pockets. Hanging hook fits shower rod or door. Water-resistant nylon. Dimensions 10x4x8 inches. Fits travel-size bottles. Full zip closure.'),
('TSA Luggage Lock 4-Digit 2pk', 'TSA recognized and accepted. 4-digit combination for 10000 options. Alloy body is durable. Flexible steel cable fits any zipper. Set your own combination. Red indicator for TSA access.'),
('Travel Adapter Universal', 'Works in 150+ countries. Covers US, EU, UK, and AU plug types. Dual USB-A and 1 USB-C port. Does not convert voltage. Compact all-in-one design. Safety shutters on outlets.'),
('Compression Socks Travel Pair', 'Graduated compression 15-20 mmHg. Prevents DVT and swelling during flights. Moisture-wicking nylon blend. Available in S through XL. Machine washable. Sold individually.'),
('Dry Bag Travel Laundry', 'Waterproof roll-top closure. 20-liter capacity. Separates dirty laundry from clean clothes. Lightweight nylon. Doubles as waterproof gear bag. Available in bright colors.'),
('Passport Holder RFID', 'RFID blocking lining protects data. Holds passport, boarding pass, and cards. Full-grain leather. Pen loop and SIM card slot. Available in 6 colors. Embossing available.'),
('Eye Mask Sleep Contoured', '3D contoured design does not touch eyelids. Memory foam conforms to face. Adjustable elastic strap. Blocks 100% of light. Includes ear plugs. Travel pouch included.'),
('Fountain Pen Converter Fill', 'Medium steel nib. Brass body with lacquer finish. Piston converter and 2 cartridges included. Posts securely. Smooth consistent ink flow. Gift box packaging.'),
('Washi Tape Set 20 Rolls', 'Decorative Japanese paper tape. Assorted patterns and widths. Repositionable adhesive. Does not damage surfaces. Ideal for journaling, scrapbooking, and gift wrapping.'),
('Mechanical Pencil Set 3-Pack', '0.5mm lead size. Metal grip section. Built-in eraser. Includes 3 tubes of HB lead refills. Click advance mechanism. Comfortable for extended writing.'),
('Ink Bottle Fountain Pen 50ml', 'Water-based dye ink. Brilliant blue-black color. 50ml glass bottle. Suitable for all fountain pens. Well opening accommodates large nibs. pH neutral for pen safety.'),
('Envelope Set Linen A7 50ct', 'Fits A7 cards 5x7 inches. Linen-textured paper. Gummed seal flap. 80lb weight. Available in white, cream, and gray. Suitable for invitations and announcements.'),
('Sealing Wax Sticks 10-Pack', 'Flexible formula works with glue gun. Rich jewel-tone colors. Each stick seals 8-10 letters. Low drip formula. Compatible with all wax seal stamps. Self-adhesive option also available.'),
('Letter Writing Set Boxed', '20 sheets of cotton paper and 10 envelopes. Deckled edges on sheets. 6x9 inch sheet size. Subtle watermark. Gift-worthy presentation box. Perfect for meaningful correspondence.'),
('Calligraphy Ink Set 12 Colors', 'Water-based pigment ink. 15ml bottles with dropper. Suitable for dip pens and brushes. Vibrant opaque colors. Lightfast and waterproof when dry. Non-clogging formula.'),
('Pen Holder Desk Ceramic', 'Handmade ceramic with glaze. 4-inch diameter, 4-inch height. Weighted base prevents tipping. Drainage hole in bottom. Each piece slightly unique. Available in 5 glazes.'),
('Index Cards Ruled 3x5 300ct', 'Heavy 110lb card stock. Blue ruled lines with red margin. Shrink-wrapped in packs of 100. Standard size fits recipe boxes and filing systems. Smudge-resistant surface.'),
('Screen Protector Tempered Glass', '9H hardness rating. 0.33mm thin. Oleophobic coating resists fingerprints. Bubble-free installation with guide frame. 2-pack includes wet and dry wipes.'),
('Phone Case Clear Slim', 'TPU bumper with polycarbonate back. Yellowing-resistant material. Raised edges protect screen and camera. Compatible with wireless charging. Lanyard hole. MIL-STD-810G tested.'),
('Cable Organizer Silicone 3pk', '5-slot design holds cables in place. Weighted silicone base stays on desk. Does not leave adhesive residue. Available in black, white, and gray. Fits cables up to 7mm.'),
('Webcam Privacy Shutter Cover', 'Metal slide mechanism. Ultra-thin 0.6mm profile. Adhesive does not obstruct camera or sensors. Works on laptops, monitors, and tablets. 3-pack in matte black.'),
('USB-C to Lightning Adapter', 'MFi certified. Supports charging and data sync. Compact design. Keychain hole. Compatible with all Lightning accessories. Enables use of USB-C cables with older iPhones.'),
('Laptop Screen Cleaner Kit', 'Streak-free cleaning solution 7oz. Includes microfiber cloth. Safe for all screens and coated optics. Ammonia and alcohol-free formula. Spray bottle is refillable.'),
('AirTag Holder Keychain 4pk', 'Scratch-resistant polycarbonate shell. Secure snap closure. Stainless steel keyring. Available in 4 colors per pack. Slim profile adds minimal bulk. IPX4 splash resistance.'),
('SIM Card Storage Case', 'Holds 6 nano SIM cards and 2 micro SIM. Eject pin built into case. Credit card size fits in wallet. Water-resistant seal. Essential for international travelers.'),
('Monitor Stand Riser Wood', 'Bamboo construction 20x8x3 inches. Elevates monitor to ergonomic height. Storage space underneath for keyboard. Supports up to 50 lbs. Non-slip rubber pads.'),
('Keyboard Cover Silicone', 'Ultra-thin 0.3mm. Washable and reusable. Protects from dust, spills, and crumbs. Custom-fit for specific laptop models. Does not affect typing feel significantly. Clear transparent.'),
('Coffee Beans Whole Medium Roast', 'Single-origin Colombian. 2lb bag with one-way valve. Roasted within 7 days of shipping. Tasting notes of chocolate and citrus. Fair trade certified.'),
('Tea Sampler Box 40 Bags', '10 varieties including green, black, herbal, and chai. Individually wrapped for freshness. Caffeine-free options included. Gift-ready packaging with descriptions. USDA organic.'),
('Protein Shaker Bottle 28oz', 'BlenderBall wire whisk mixes smooth. Leak-proof screw-on lid. BPA-free Tritan plastic. Dishwasher safe. Measurement markings on side. Carrying loop on lid.'),
('Insulated Tumbler 20oz', 'Double-wall vacuum insulation. Keeps drinks hot 4 hours or cold 12. Splash-proof sliding lid. 18/8 stainless steel. Fits standard cup holders. Powder-coated exterior.'),
('Water Infuser Pitcher 2.5L', 'Removable infuser core for fruit and herbs. BPA-free Tritan plastic. Flip-top lid pours easily. Fits in refrigerator door. Dishwasher safe. Silicone seal prevents leaks.');
